title: efe_ertugrul
description: apple developer
show_downloads: false
google_analytics: UA-34720961-1
theme: jekyll-theme-hacker
homepage:
  homepage_url: https://efeertugrul.com/
technotes:
  technotes_url: https://efeertugrul.com/tech_notes/tech-notes
app_store:
  appstore_url: https://apps.apple.com/developer/efe-ertugrul/id894567261
github:
  github_url: https://github.com/retrokid
stackoverflow:
  stackoverflow_url: https://stackoverflow.com/users/2122253/efe
devto:
  devto_url: https://dev.to/efe
  