title: efe_ertugrul
description: apple developer
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  repository_url: https://github.com/retrokid
  twitter_url: twitter.com
  stackoverflow_url: stackoverflow.com
  medium_url: medium.com
