title: efe_ertugrul
description: apple developer
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  repository_url: https://github.com/retrokid
  stackoverflow_url: https://stackoverflow.com/users/2122253/efe
  medium_url: https://medium.com/@appledeveloper0
twitter:
  twitter_url: https://twitter.com/appledeveloper0
  
