title: efe_ertugrul
description: apple developer
show_downloads: false
google_analytics: UA-34720961-1
theme: jekyll-theme-hacker
homepage:
  homepage_url: http://efeertugrul.com/
technotes:
  technotes_url: http://efeertugrul.com/tech_notes/tech-notes
github:
  github_url: https://github.com/retrokid
twitter:
  twitter_url: https://twitter.com/efeertugrul_
stackoverflow:
  stackoverflow_url: https://stackoverflow.com/users/2122253/efe
app_store:
  appstore_url: https://apps.apple.com/developer/efe-ertugrul/id894567261
devto:
  devto_url: https://dev.to/efe
  
